v1.10.0 * Close #210: Classic era support (#211) * Close #209: Click for tooltip (#215) * Close #216: Add row border configurations (#218) * Close #187: More configuration options (#221)

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -21,16 +21,24 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
-          python-version: 3.x
+          python-version: 3.13
 
-      - name: Install Python dependencies
-        run: pip install -r requirements.txt
+      - name: Install Poetry
+        uses: snok/install-poetry@v1
+        with:
+          version: 1.8.5
+
+      - name: Install dependencies
+        run: poetry install
 
       - name: Run translation check script
-        run: python .scripts/missing_translation_check.py
+        run: poetry run python .scripts/missing_translation_check.py
 
       - name: Check for Hard-coded strings
-        run: python .scripts/hardcode_string_check.py
+        run: poetry run python .scripts/hardcode_string_check.py
+
+      - name: Run missing locale keys script
+        run: poetry run python .scripts/check_for_missing_locale_keys.py
 
   run_tests:
     runs-on: ubuntu-latest
@@ -152,3 +160,25 @@ jobs:
                 body: `${commentIdentifier}\n${commentBody}`
               });
             }
+
+  all_pr_checks:
+    name: Passing PR Checks
+    runs-on: ubuntu-latest
+    needs: [check_translations, run_tests, test_package]
+    steps:
+      - name: Export needs results as JSON
+        id: export-needs
+        run: echo '${{ toJSON(needs) }}' > needs.json
+
+      - name: Check if all jobs passed or were skipped
+        run: |
+          needs=$(cat needs.json)
+          for job in $(echo "$needs" | jq -r 'keys[]'); do
+            result=$(echo "$needs" | jq -r ".\"$job\".result")
+            if [[ "$result" != "success" && "$result" != "skipped" ]]; then
+              echo "Job $job failed."
+              exit 1
+            fi
+          done
+          echo "All jobs passed or were skipped."
+        shell: bash
